apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
      - name: pokedex-app
        image: pokedex-app:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000